### ISSUE TITLE
showPage does not display explorer tree

### ISSUE THREAD

**Issue by NiPfi** [NiPfi/MockLearningmodule#3]

**Comment by GerberFlorian** [comment]
the issue only occours in the edit and the metadata subtab of the page. Seems to be a template related issue

**Comment by Eagle94T** [comment]
The 'arrows' to fold the Chapters/Subchapters are still missing

**Comment by NiPfi** [comment]
@Eagle94T Are you sure? Have you tried emptying your browsers cache etc.? There is no issue on my end.
![image](https://cloud.githubusercontent.com/assets/1059042/14766219/f94e4ee4-0a01-11e6-8d3c-afe4acdf7c52.png)

**Comment by Eagle94T** [comment]
@NiPfi yes I'm sure, but the issue with the arrows only happens in the metadata subtab for a page! Because there i needed to remove the "ilNoDisplay" and add some other classes with JS

**Comment by NiPfi** [comment]
Metadata Subtab on Chapter hides tree as well

**Comment by Eagle94T** [comment]
Metadata Subtab on Settings also hides it
